In [1]:
import pandas as pd

In [2]:
# 1) 파일 불러오기
df_main = pd.read_csv("../../data/Crawling_data/daily_counts.csv")
df_insta = pd.read_csv("../../data/Crawling_data/instagram_daily_counts(25.12.15~26.03.06).csv")
df_cafe = pd.read_csv("../../data/Crawling_data/naver_cafe_daily_counts.csv")

In [3]:
df_main.head(9)

,target_date,platform,keyword,count,collected_at,status,note
0,2025-12-15,naver_blog,렉스트림,1,2026-03-31 9:29,success,NaN
1,2025-12-15,naver_news,렉스트림,0,2026-03-31 9:29,success,NaN
2,2025-12-15,youtube,렉스트림,0,2026-03-31 9:29,success,NaN
3,2025-12-15,naver_blog,REXTREME,1,2026-03-31 9:29,success,NaN
4,2025-12-15,naver_news,REXTREME,0,2026-03-31 9:29,success,NaN
5,2025-12-15,youtube,REXTREME,4,2026-03-31 9:29,success,NaN
6,2025-12-15,naver_blog,combined_unique,1,2026-03-31 9:29,success,NaN
7,2025-12-15,naver_news,combined_unique,0,2026-03-31 9:29,success,NaN
8,2025-12-15,youtube,combined_unique,4,2026-03-31 9:29,success,NaN

In [4]:
df_insta.head(9)

,target_date,platform,keyword,count,collected_at,status,note
0,2025-12-15,instagram,렉스트림,6,2026-03-23 16:37:00,success,NaN
1,2025-12-15,instagram,REXTREME,5,2026-03-23 16:37:00,success,NaN
2,2025-12-15,instagram,combined_unique,6,2026-03-23 16:37:00,success,NaN
3,2025-12-16,instagram,렉스트림,1,2026-03-23 16:37:00,success,NaN
4,2025-12-16,instagram,REXTREME,1,2026-03-23 16:37:00,success,NaN
5,2025-12-16,instagram,combined_unique,2,2026-03-23 16:37:00,success,NaN
6,2025-12-17,instagram,렉스트림,2,2026-03-23 16:37:00,success,NaN
7,2025-12-17,instagram,REXTREME,2,2026-03-23 16:37:00,success,NaN
8,2025-12-17,instagram,combined_unique,2,2026-03-23 16:37:00,success,NaN

In [5]:
df_cafe.head(9)

,target_date,platform,keyword,count,collected_at,status,note
0,2025-12-15,naver_cafe,렉스트림,0,2026-04-06 16:10:14,success,NaN
1,2025-12-15,naver_cafe,REXTREME,0,2026-04-06 16:10:14,success,NaN
2,2025-12-15,naver_cafe,combined_unique,0,2026-04-06 16:10:14,success,NaN
3,2025-12-16,naver_cafe,렉스트림,0,2026-04-06 16:10:14,success,NaN
4,2025-12-16,naver_cafe,REXTREME,0,2026-04-06 16:10:14,success,NaN
5,2025-12-16,naver_cafe,combined_unique,0,2026-04-06 16:10:14,success,NaN
6,2025-12-17,naver_cafe,렉스트림,0,2026-04-06 16:10:14,success,NaN
7,2025-12-17,naver_cafe,REXTREME,0,2026-04-06 16:10:14,success,NaN
8,2025-12-17,naver_cafe,combined_unique,0,2026-04-06 16:10:14,success,NaN

In [6]:
# 2) keyword 이름 통일
df_main["keyword"] = df_main["keyword"].replace({
    "combined_unique_url": "combined_unique"
})
df_cafe["keyword"] = df_cafe["keyword"].replace({
    "combined_unique_url": "combined_unique"
})

In [7]:
df_main.head(9)

,target_date,platform,keyword,count,collected_at,status,note
0,2025-12-15,naver_blog,렉스트림,1,2026-03-31 9:29,success,NaN
1,2025-12-15,naver_news,렉스트림,0,2026-03-31 9:29,success,NaN
2,2025-12-15,youtube,렉스트림,0,2026-03-31 9:29,success,NaN
3,2025-12-15,naver_blog,REXTREME,1,2026-03-31 9:29,success,NaN
4,2025-12-15,naver_news,REXTREME,0,2026-03-31 9:29,success,NaN
5,2025-12-15,youtube,REXTREME,4,2026-03-31 9:29,success,NaN
6,2025-12-15,naver_blog,combined_unique,1,2026-03-31 9:29,success,NaN
7,2025-12-15,naver_news,combined_unique,0,2026-03-31 9:29,success,NaN
8,2025-12-15,youtube,combined_unique,4,2026-03-31 9:29,success,NaN

In [8]:
df_cafe.head(9)

,target_date,platform,keyword,count,collected_at,status,note
0,2025-12-15,naver_cafe,렉스트림,0,2026-04-06 16:10:14,success,NaN
1,2025-12-15,naver_cafe,REXTREME,0,2026-04-06 16:10:14,success,NaN
2,2025-12-15,naver_cafe,combined_unique,0,2026-04-06 16:10:14,success,NaN
3,2025-12-16,naver_cafe,렉스트림,0,2026-04-06 16:10:14,success,NaN
4,2025-12-16,naver_cafe,REXTREME,0,2026-04-06 16:10:14,success,NaN
5,2025-12-16,naver_cafe,combined_unique,0,2026-04-06 16:10:14,success,NaN
6,2025-12-17,naver_cafe,렉스트림,0,2026-04-06 16:10:14,success,NaN
7,2025-12-17,naver_cafe,REXTREME,0,2026-04-06 16:10:14,success,NaN
8,2025-12-17,naver_cafe,combined_unique,0,2026-04-06 16:10:14,success,NaN

In [9]:
# 3) 컬럼 순서 통일
cols = ["target_date", "platform", "keyword", "count", "collected_at", "status", "note"]

df_main = df_main[cols].copy()
df_insta = df_insta[cols].copy()
df_cafe = df_cafe[cols].copy()

In [10]:
# 4) 세로 결합
df_tableau = pd.concat([df_main, df_insta, df_cafe], ignore_index=True)

In [11]:
df_tableau.head(9)

,target_date,platform,keyword,count,collected_at,status,note
0,2025-12-15,naver_blog,렉스트림,1,2026-03-31 9:29,success,NaN
1,2025-12-15,naver_news,렉스트림,0,2026-03-31 9:29,success,NaN
2,2025-12-15,youtube,렉스트림,0,2026-03-31 9:29,success,NaN
3,2025-12-15,naver_blog,REXTREME,1,2026-03-31 9:29,success,NaN
4,2025-12-15,naver_news,REXTREME,0,2026-03-31 9:29,success,NaN
5,2025-12-15,youtube,REXTREME,4,2026-03-31 9:29,success,NaN
6,2025-12-15,naver_blog,combined_unique,1,2026-03-31 9:29,success,NaN
7,2025-12-15,naver_news,combined_unique,0,2026-03-31 9:29,success,NaN
8,2025-12-15,youtube,combined_unique,4,2026-03-31 9:29,success,NaN

In [12]:
# 5) status 성공 데이터만 남기고 싶으면
df_tableau = df_tableau[df_tableau["status"] == "success"].copy()

In [13]:
# 6) 날짜형 변환
df_tableau["target_date"] = pd.to_datetime(df_tableau["target_date"], errors="coerce")

In [14]:
# 7) 정렬
platform_order = ["naver_blog", "naver_cafe", "naver_news", "youtube", "instagram"]
keyword_order = ["렉스트림", "REXTREME", "combined_unique"]

df_tableau["platform"] = pd.Categorical(
    df_tableau["platform"],
    categories=platform_order,
    ordered=True
)

df_tableau["keyword"] = pd.Categorical(
    df_tableau["keyword"],
    categories=keyword_order,
    ordered=True
)

df_tableau = df_tableau.sort_values(["target_date", "platform", "keyword"]).reset_index(drop=True)

In [15]:
# 8) 저장
df_tableau.to_csv(
    "../../data/Crawling_data/tableau_all_platform_union.csv",
    index=False,
    encoding="utf-8-sig"
)

df_tableau.head(20)

,target_date,platform,keyword,count,collected_at,status,note
0,2025-12-15,naver_blog,렉스트림,1,2026-03-31 9:29,success,NaN
1,2025-12-15,naver_blog,REXTREME,1,2026-03-31 9:29,success,NaN
2,2025-12-15,naver_blog,combined_unique,1,2026-03-31 9:29,success,NaN
3,2025-12-15,naver_cafe,렉스트림,0,2026-04-06 16:10:14,success,NaN
4,2025-12-15,naver_cafe,REXTREME,0,2026-04-06 16:10:14,success,NaN
5,2025-12-15,naver_cafe,combined_unique,0,2026-04-06 16:10:14,success,NaN
6,2025-12-15,naver_news,렉스트림,0,2026-03-31 9:29,success,NaN
7,2025-12-15,naver_news,REXTREME,0,2026-03-31 9:29,success,NaN
8,2025-12-15,naver_news,combined_unique,0,2026-03-31 9:29,success,NaN
9,2025-12-15,youtube,렉스트림,0,2026-03-31 9:29,success,NaN
10,2025-12-15,youtube,REXTREME,4,2026-03-31 9:29,success,NaN
11,2025-12-15,youtube,combined_unique,4,2026-03-31 9:29,success,NaN
12,2025-12-15,instagram,렉스트림,6,2026-03-23 16:37:00,success,NaN
13,2025-12-15,instagram,REXTREME,5,2026-03-23 16:37:00,success,NaN
14,2025-12-15,instagram,combined_unique,6,2026-03-23 16:37:00,success,NaN
15,2025-12-16,naver_blog,렉스트림,0,2026-03-31 9:29,success,NaN
16,2025-12-16,naver_blog,REXTREME,0,2026-03-31 9:29,success,NaN
17,2025-12-16,naver_blog,combined_unique,0,2026-03-31 9:29,success,NaN
18,2025-12-16,naver_cafe,렉스트림,0,2026-04-06 16:10:14,success,NaN
19,2025-12-16,naver_cafe,REXTREME,0,2026-04-06 16:10:14,success,NaN